name: my-first-action
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependancies 
        run: npm ci 
      - name: Run tests
        run: npm test 
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "linting job" 
      - name: Build
        run: echo "building job"
